"""add_external_db_config_ids_to_mcpversion

Revision ID: 555112d4a575
Revises: 42601a77e740
Create Date: 2024-07-15 15:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '555112d4a575'
down_revision: Union[str, None] = '42601a77e740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_versions', sa.Column('external_db_config_ids',
                  postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_versions', 'external_db_config_ids')
    # ### end Alembic commands ###
