"""create_action_logs_table

Revision ID: a6bbd345eff9
Revises: 555112d4a575
Create Date: 2024-07-16 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a6bbd345eff9'
down_revision: Union[str, None] = '555112d4a575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_logs',
                    sa.Column('id', postgresql.UUID(
                        as_uuid=True), nullable=False),
                    sa.Column('timestamp', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('actor_id', sa.String(), nullable=True),
                    sa.Column('action_type', sa.String(), nullable=False),
                    sa.Column('entity_type', sa.String(), nullable=True),
                    sa.Column('entity_id', sa.String(), nullable=True),
                    sa.Column('details', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_logs'))
                    )
    op.create_index(op.f('ix_action_logs_actor_id'),
                    'action_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_action_logs_action_type'),
                    'action_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_action_logs_entity_id'),
                    'action_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_action_logs_entity_type'),
                    'action_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_action_logs_timestamp'),
                    'action_logs', ['timestamp'], unique=False)
    # Example for composite index if needed later:
    # op.create_index(op.f('ix_action_logs_entity_type_id'), 'action_logs', ['entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_action_logs_entity_type_id'), table_name='action_logs') # If composite index was created
    op.drop_index(op.f('ix_action_logs_timestamp'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_entity_type'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_entity_id'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_action_type'), table_name='action_logs')
    op.drop_index(op.f('ix_action_logs_actor_id'), table_name='action_logs')
    op.drop_table('action_logs')
    # ### end Alembic commands ###
